import type { AppData } from "./types";
import { addDaysISO, todayISO } from "./utils";

const T = todayISO();
const d = (n: number) => addDaysISO(n);

export const seedData: AppData = {
  settings: {
    applicantName: "Alex Chen",
    cycle: "2026–27",
    timezone: "America/New_York",
    accentColor: "forest",
  },

  schools: [
    { id: "sch_stanford", name: "Stanford University", shortName: "Stanford", location: "Stanford, CA", website: "https://www.stanford.edu" },
    { id: "sch_mit", name: "Massachusetts Institute of Technology", shortName: "MIT", location: "Cambridge, MA", website: "https://www.mit.edu" },
    { id: "sch_cmu", name: "Carnegie Mellon University", shortName: "CMU", location: "Pittsburgh, PA", website: "https://www.cmu.edu" },
    { id: "sch_princeton", name: "Princeton University", shortName: "Princeton", location: "Princeton, NJ", website: "https://www.princeton.edu" },
    { id: "sch_berkeley", name: "UC Berkeley", shortName: "Berkeley", location: "Berkeley, CA", website: "https://www.berkeley.edu" },
    { id: "sch_uw", name: "University of Washington", shortName: "UW", location: "Seattle, WA", website: "https://www.washington.edu" },
    { id: "sch_cornell", name: "Cornell University", shortName: "Cornell", location: "Ithaca, NY", website: "https://www.cornell.edu" },
    { id: "sch_uiuc", name: "University of Illinois Urbana-Champaign", shortName: "UIUC", location: "Urbana, IL", website: "https://illinois.edu" },
    { id: "sch_columbia", name: "Columbia University", shortName: "Columbia", location: "New York, NY", website: "https://www.columbia.edu" },
    { id: "sch_yale", name: "Yale University", shortName: "Yale", location: "New Haven, CT", website: "https://www.yale.edu" },
  ],

  programs: [
    { id: "prg_stanford_cs", schoolId: "sch_stanford", name: "Computer Science", degree: "PhD", department: "CS", website: "https://cs.stanford.edu" },
    { id: "prg_mit_eecs", schoolId: "sch_mit", name: "EECS", degree: "PhD", department: "EECS", website: "https://www.eecs.mit.edu" },
    { id: "prg_cmu_cs", schoolId: "sch_cmu", name: "Computer Science", degree: "PhD", department: "SCS", website: "https://cs.cmu.edu" },
    { id: "prg_princeton_cs", schoolId: "sch_princeton", name: "Computer Science", degree: "PhD", department: "COS", website: "https://www.cs.princeton.edu" },
    { id: "prg_berkeley_eecs", schoolId: "sch_berkeley", name: "EECS", degree: "PhD", department: "EECS", website: "https://eecs.berkeley.edu" },
    { id: "prg_uw_cse", schoolId: "sch_uw", name: "Computer Science & Engineering", degree: "PhD", department: "CSE", website: "https://www.cs.washington.edu" },
    { id: "prg_cornell_cs", schoolId: "sch_cornell", name: "Computer Science", degree: "PhD", department: "CS", website: "https://www.cs.cornell.edu" },
    { id: "prg_uiuc_cs", schoolId: "sch_uiuc", name: "Computer Science", degree: "PhD", department: "CS", website: "https://cs.illinois.edu" },
    { id: "prg_columbia_cs", schoolId: "sch_columbia", name: "Computer Science", degree: "PhD", department: "CS", website: "https://www.cs.columbia.edu" },
    { id: "prg_yale_cs", schoolId: "sch_yale", name: "Computer Science", degree: "PhD", department: "CS", website: "https://cpsc.yale.edu" },
  ],

  applications: [
    { id: "app_stanford", schoolId: "sch_stanford", programId: "prg_stanford_cs", cycle: "2026–27", status: "Preparing", deadline: "2026-12-01", funding: "Fellowship preferred", notes: "Strong alignment with unlearning & agents groups.", nextActionTaskId: "task_stanford_sop", createdAt: "2026-08-01", updatedAt: T },
    { id: "app_mit", schoolId: "sch_mit", programId: "prg_mit_eecs", cycle: "2026–27", status: "Researching", deadline: "2026-12-01", funding: "RA/TA", notes: "Focus on alignment & program synthesis faculty.", nextActionTaskId: "task_mit_read", createdAt: "2026-08-02", updatedAt: T },
    { id: "app_cmu", schoolId: "sch_cmu", programId: "prg_cmu_cs", cycle: "2026–27", status: "Preparing", deadline: "2026-12-15", funding: "RA", nextActionTaskId: "task_cmu_rec", createdAt: "2026-08-03", updatedAt: T },
    { id: "app_princeton", schoolId: "sch_princeton", programId: "prg_princeton_cs", cycle: "2026–27", status: "Researching", deadline: "2026-12-15", funding: "Fellowship", notes: "Professor Chen is primary fit.", nextActionTaskId: "task_email_chen", createdAt: "2026-08-05", updatedAt: T },
    { id: "app_berkeley", schoolId: "sch_berkeley", programId: "prg_berkeley_eecs", cycle: "2026–27", status: "Interested", deadline: "2026-12-08", funding: "Unknown", createdAt: "2026-08-10", updatedAt: T },
    { id: "app_uw", schoolId: "sch_uw", programId: "prg_uw_cse", cycle: "2026–27", status: "Ready to Submit", deadline: "2026-12-15", funding: "RA/TA", nextActionTaskId: "task_uw_submit", createdAt: "2026-08-12", updatedAt: T },
    { id: "app_cornell", schoolId: "sch_cornell", programId: "prg_cornell_cs", cycle: "2026–27", status: "Preparing", deadline: "2027-01-02", funding: "Fellowship", createdAt: "2026-08-15", updatedAt: T },
    { id: "app_uiuc", schoolId: "sch_uiuc", programId: "prg_uiuc_cs", cycle: "2026–27", status: "Interested", deadline: "2026-12-15", funding: "RA", createdAt: "2026-08-18", updatedAt: T },
    { id: "app_columbia", schoolId: "sch_columbia", programId: "prg_columbia_cs", cycle: "2026–27", status: "Submitted", deadline: "2026-12-15", funding: "RA/TA", createdAt: "2026-07-20", updatedAt: d(-5) },
    { id: "app_yale", schoolId: "sch_yale", programId: "prg_yale_cs", cycle: "2026–27", status: "Interview", deadline: "2026-12-15", funding: "Fellowship", createdAt: "2026-07-15", updatedAt: d(-2) },
  ],

  professors: [
    { id: "prof_chen", name: "Prof. Wei Chen", title: "Associate Professor", institution: "Princeton University", schoolId: "sch_princeton", email: "wchen@cs.princeton.edu", website: "https://example.edu/wchen", researchAreas: ["Machine Unlearning", "Privacy", "Trustworthy ML"], lookingForStudents: true, expectations: ["Looking for PhD students", "Strong ML background", "Research experience preferred"], expectationsSource: "Lab FAQ · Aug 2026", expectationsUpdatedAt: "2026-08-20", notes: "Primary Princeton fit.", createdAt: "2026-08-05" },
    { id: "prof_smith", name: "Prof. Elena Smith", title: "Professor", institution: "Stanford University", schoolId: "sch_stanford", email: "esmith@cs.stanford.edu", website: "https://example.edu/esmith", researchAreas: ["LLM Alignment", "AI Safety", "RLHF"], lookingForStudents: true, expectations: ["Looking for PhD students", "Prior publication preferred"], expectationsSource: "Homepage", expectationsUpdatedAt: "2026-09-01", createdAt: "2026-08-01" },
    { id: "prof_park", name: "Prof. Min Park", title: "Assistant Professor", institution: "MIT", schoolId: "sch_mit", email: "mpark@mit.edu", researchAreas: ["Program Search", "Neuro-symbolic AI", "Code Generation"], lookingForStudents: true, expectations: ["Strong systems or PL background"], createdAt: "2026-08-02" },
    { id: "prof_nguyen", name: "Prof. Linh Nguyen", title: "Associate Professor", institution: "Carnegie Mellon University", schoolId: "sch_cmu", email: "lnguyen@cs.cmu.edu", researchAreas: ["AI Agents", "Tool Use", "Multi-agent Systems"], lookingForStudents: true, createdAt: "2026-08-03" },
    { id: "prof_rossi", name: "Prof. Marco Rossi", title: "Professor", institution: "UC Berkeley", schoolId: "sch_berkeley", researchAreas: ["LLM Optimization", "Efficient Training", "Inference"], lookingForStudents: false, createdAt: "2026-08-10" },
    { id: "prof_kim", name: "Prof. Soo-Jin Kim", title: "Assistant Professor", institution: "University of Washington", schoolId: "sch_uw", researchAreas: ["Machine Unlearning", "Data Attribution"], lookingForStudents: true, createdAt: "2026-08-12" },
    { id: "prof_patel", name: "Prof. Anika Patel", title: "Associate Professor", institution: "Cornell University", schoolId: "sch_cornell", researchAreas: ["LLM Alignment", "Interpretability"], lookingForStudents: true, createdAt: "2026-08-15" },
    { id: "prof_owens", name: "Prof. David Owens", title: "Professor", institution: "Stanford University", schoolId: "sch_stanford", researchAreas: ["Program Search", "Program Synthesis"], lookingForStudents: true, createdAt: "2026-08-01" },
    { id: "prof_berg", name: "Prof. Hannah Berg", title: "Assistant Professor", institution: "Yale University", schoolId: "sch_yale", researchAreas: ["AI Agents", "Human-AI Interaction"], lookingForStudents: true, createdAt: "2026-07-20" },
    { id: "prof_zhao", name: "Prof. Rui Zhao", title: "Associate Professor", institution: "Columbia University", schoolId: "sch_columbia", researchAreas: ["Privacy", "Federated Learning"], lookingForStudents: true, createdAt: "2026-07-22" },
    { id: "prof_lee", name: "Prof. James Lee", title: "Professor", institution: "UIUC", schoolId: "sch_uiuc", researchAreas: ["LLM Optimization", "Distributed Systems"], lookingForStudents: true, createdAt: "2026-08-18" },
    { id: "prof_martin", name: "Prof. Clara Martin", title: "Assistant Professor", institution: "MIT", schoolId: "sch_mit", researchAreas: ["Machine Unlearning", "Continual Learning"], lookingForStudents: true, createdAt: "2026-08-08" },
    { id: "prof_huang", name: "Prof. Yi Huang", title: "Associate Professor", institution: "CMU", schoolId: "sch_cmu", researchAreas: ["Trustworthy ML", "Robustness"], lookingForStudents: true, createdAt: "2026-08-09" },
    { id: "prof_diaz", name: "Prof. Sofia Diaz", title: "Professor", institution: "Princeton University", schoolId: "sch_princeton", researchAreas: ["NLP", "Alignment Evaluation"], lookingForStudents: false, createdAt: "2026-08-11" },
    { id: "prof_okonkwo", name: "Prof. Chidi Okonkwo", title: "Assistant Professor", institution: "UC Berkeley", schoolId: "sch_berkeley", researchAreas: ["AI Agents", "Planning"], lookingForStudents: true, createdAt: "2026-08-14" },
  ],

  professorFits: [
    { id: "fit_chen_princeton", professorId: "prof_chen", applicationId: "app_princeton", overallFit: 9.3, researchAlignment: 9.5, recentWork: 9.0, methodology: 8.8, applicationRelevance: 9.2, priority: "High", contactStatus: "Waiting", whyFit: "Strong overlap with machine unlearning and program search.", followUpDate: d(2), notes: "Emailed Sep 1; awaiting reply." },
    { id: "fit_smith_stanford", professorId: "prof_smith", applicationId: "app_stanford", overallFit: 9.1, researchAlignment: 9.4, recentWork: 9.0, methodology: 8.7, applicationRelevance: 9.0, priority: "High", contactStatus: "Replied", whyFit: "Alignment work maps closely to my safety internship." },
    { id: "fit_owens_stanford", professorId: "prof_owens", applicationId: "app_stanford", overallFit: 8.4, researchAlignment: 8.6, recentWork: 8.2, methodology: 8.5, applicationRelevance: 8.3, priority: "Medium", contactStatus: "Contacted" },
    { id: "fit_park_mit", professorId: "prof_park", applicationId: "app_mit", overallFit: 8.9, researchAlignment: 9.2, recentWork: 8.8, methodology: 8.7, applicationRelevance: 8.9, priority: "High", contactStatus: "Drafted" },
    { id: "fit_martin_mit", professorId: "prof_martin", applicationId: "app_mit", overallFit: 8.2, researchAlignment: 8.5, recentWork: 8.0, methodology: 8.1, applicationRelevance: 8.3, priority: "Medium", contactStatus: "Not Contacted" },
    { id: "fit_nguyen_cmu", professorId: "prof_nguyen", applicationId: "app_cmu", overallFit: 8.7, researchAlignment: 8.9, recentWork: 8.6, methodology: 8.4, applicationRelevance: 8.8, priority: "High", contactStatus: "Follow-up Due", followUpDate: d(-1) },
    { id: "fit_huang_cmu", professorId: "prof_huang", applicationId: "app_cmu", overallFit: 7.9, researchAlignment: 8.0, recentWork: 7.8, methodology: 7.7, applicationRelevance: 7.9, priority: "Medium", contactStatus: "Not Contacted" },
    { id: "fit_kim_uw", professorId: "prof_kim", applicationId: "app_uw", overallFit: 8.8, researchAlignment: 9.0, recentWork: 8.7, methodology: 8.5, applicationRelevance: 8.9, priority: "High", contactStatus: "Replied" },
    { id: "fit_patel_cornell", professorId: "prof_patel", applicationId: "app_cornell", overallFit: 8.3, researchAlignment: 8.6, recentWork: 8.1, methodology: 8.0, applicationRelevance: 8.2, priority: "High", contactStatus: "Not Contacted" },
    { id: "fit_berg_yale", professorId: "prof_berg", applicationId: "app_yale", overallFit: 8.5, researchAlignment: 8.7, recentWork: 8.4, methodology: 8.2, applicationRelevance: 8.6, priority: "High", contactStatus: "Replied" },
    { id: "fit_zhao_columbia", professorId: "prof_zhao", applicationId: "app_columbia", overallFit: 7.8, researchAlignment: 8.0, recentWork: 7.6, methodology: 7.7, applicationRelevance: 7.9, priority: "Medium", contactStatus: "Archived" },
    { id: "fit_chen_stanford", professorId: "prof_chen", applicationId: "app_stanford", overallFit: 8.7, researchAlignment: 8.9, recentWork: 8.5, methodology: 8.4, applicationRelevance: 8.6, priority: "Medium", contactStatus: "Not Contacted", whyFit: "Secondary fit if Princeton capacity is limited." },
  ],

  researchTopics: [
    { id: "topic_unlearning", name: "Machine Unlearning", description: "Efficient removal of training influence from models.", professorIds: ["prof_chen", "prof_kim", "prof_martin"], applicationIds: ["app_princeton", "app_uw", "app_stanford", "app_mit"] },
    { id: "topic_alignment", name: "LLM Alignment", description: "Aligning model behavior with human intent and values.", professorIds: ["prof_smith", "prof_patel", "prof_diaz"], applicationIds: ["app_stanford", "app_cornell"] },
    { id: "topic_search", name: "Program Search", description: "Search and synthesis over program spaces.", professorIds: ["prof_park", "prof_owens"], applicationIds: ["app_mit", "app_stanford"] },
    { id: "topic_agents", name: "AI Agents", description: "Tool-using and multi-agent systems.", professorIds: ["prof_nguyen", "prof_berg", "prof_okonkwo"], applicationIds: ["app_cmu", "app_yale", "app_berkeley"] },
    { id: "topic_opt", name: "LLM Optimization", description: "Training and inference efficiency.", professorIds: ["prof_rossi", "prof_lee"], applicationIds: ["app_berkeley", "app_uiuc"] },
    { id: "topic_privacy", name: "Privacy & Trustworthy ML", description: "Privacy-preserving and robust learning.", professorIds: ["prof_chen", "prof_zhao", "prof_huang"], applicationIds: ["app_princeton", "app_columbia", "app_cmu"] },
  ],

  papers: [
    { id: "paper_1", title: "Exact Machine Unlearning via Influence Recomputation", authors: ["Wei Chen", "A. Brooks"], venue: "NeurIPS", year: 2025, url: "https://example.edu/papers/exact-unlearning", topicIds: ["topic_unlearning"], professorIds: ["prof_chen"], relevance: 9.5, whyMatters: "Core method for certified forgetting.", keyIdea: "Recompute influence scores with sparse Hessian approximations.", myThoughts: "Could connect to my internship on data deletion APIs.", potentialConnection: "Natural bridge to Princeton application narrative.", createdAt: "2026-08-06" },
    { id: "paper_2", title: "Scalable Unlearning for Large Language Models", authors: ["Soo-Jin Kim", "L. Tran"], venue: "ICML", year: 2025, topicIds: ["topic_unlearning"], professorIds: ["prof_kim"], relevance: 9.0, whyMatters: "Shows practical unlearning at LLM scale.", createdAt: "2026-08-13" },
    { id: "paper_3", title: "Preference Optimization without Preference Noise", authors: ["Elena Smith", "R. Cole"], venue: "ICLR", year: 2025, topicIds: ["topic_alignment"], professorIds: ["prof_smith"], relevance: 9.2, keyIdea: "Noise-aware preference modeling improves alignment stability.", createdAt: "2026-08-02" },
    { id: "paper_4", title: "Neural Program Search with Verified Specs", authors: ["Min Park"], venue: "PLDI", year: 2024, topicIds: ["topic_search"], professorIds: ["prof_park"], relevance: 8.8, createdAt: "2026-08-04" },
    { id: "paper_5", title: "Tool-Using Agents with Hierarchical Memory", authors: ["Linh Nguyen", "K. Adeyemi"], venue: "NeurIPS", year: 2025, topicIds: ["topic_agents"], professorIds: ["prof_nguyen"], relevance: 8.7, createdAt: "2026-08-07" },
    { id: "paper_6", title: "Inference-Time Optimization for Long-Context LLMs", authors: ["Marco Rossi"], venue: "MLSys", year: 2025, topicIds: ["topic_opt"], professorIds: ["prof_rossi"], relevance: 7.5, createdAt: "2026-08-11" },
    { id: "paper_7", title: "Continual Unlearning under Distribution Shift", authors: ["Clara Martin"], venue: "AAAI", year: 2025, topicIds: ["topic_unlearning"], professorIds: ["prof_martin"], relevance: 8.4, createdAt: "2026-08-09" },
    { id: "paper_8", title: "Evaluating Alignment with Behavioral Specs", authors: ["Anika Patel"], venue: "ACL", year: 2025, topicIds: ["topic_alignment"], professorIds: ["prof_patel"], relevance: 8.1, createdAt: "2026-08-16" },
    { id: "paper_9", title: "Multi-Agent Debate for Tool Selection", authors: ["Hannah Berg"], venue: "EMNLP", year: 2024, topicIds: ["topic_agents"], professorIds: ["prof_berg"], relevance: 8.0, createdAt: "2026-07-25" },
    { id: "paper_10", title: "Federated Unlearning with Client Drift Control", authors: ["Rui Zhao"], venue: "CCS", year: 2024, topicIds: ["topic_privacy", "topic_unlearning"], professorIds: ["prof_zhao"], relevance: 7.6, createdAt: "2026-07-28" },
    { id: "paper_11", title: "Program Synthesis via Learned Search Heuristics", authors: ["David Owens", "T. Hale"], venue: "OOPSLA", year: 2024, topicIds: ["topic_search"], professorIds: ["prof_owens"], relevance: 8.3, createdAt: "2026-08-03" },
    { id: "paper_12", title: "Robustness Certificates for Preference Models", authors: ["Yi Huang"], venue: "ICML", year: 2025, topicIds: ["topic_privacy"], professorIds: ["prof_huang"], relevance: 7.8, createdAt: "2026-08-10" },
    { id: "paper_13", title: "Planning-Aware Agent Architectures", authors: ["Chidi Okonkwo"], venue: "ICLR", year: 2025, topicIds: ["topic_agents"], professorIds: ["prof_okonkwo"], relevance: 7.9, createdAt: "2026-08-15" },
    { id: "paper_14", title: "Distributed Low-Rank Adaptation at Scale", authors: ["James Lee"], venue: "NSDI", year: 2025, topicIds: ["topic_opt"], professorIds: ["prof_lee"], relevance: 7.2, createdAt: "2026-08-19" },
    { id: "paper_15", title: "Human Oversight Interfaces for Agent Workflows", authors: ["Hannah Berg", "M. Ellis"], venue: "CHI", year: 2025, topicIds: ["topic_agents"], professorIds: ["prof_berg"], relevance: 7.7, createdAt: "2026-07-30" },
    { id: "paper_16", title: "Approximate Unlearning with Traceable Deletion Logs", authors: ["Wei Chen"], venue: "S&P", year: 2024, topicIds: ["topic_unlearning", "topic_privacy"], professorIds: ["prof_chen"], relevance: 9.1, myThoughts: "Useful citation for SOP privacy paragraph.", createdAt: "2026-08-06" },
    { id: "paper_17", title: "Calibration Failures in Aligned Models", authors: ["Sofia Diaz"], venue: "FAccT", year: 2025, topicIds: ["topic_alignment"], professorIds: ["prof_diaz"], relevance: 7.4, createdAt: "2026-08-12" },
    { id: "paper_18", title: "Spec-Guided Repair for Generated Programs", authors: ["Min Park", "J. Orth"], venue: "ASE", year: 2025, topicIds: ["topic_search"], professorIds: ["prof_park"], relevance: 8.5, createdAt: "2026-08-05" },
  ],

  tasks: [
    { id: "task_stanford_sop", title: "Finish Stanford SOP", status: "In Progress", priority: "Urgent", dueDate: d(1), applicationId: "app_stanford", documentId: "doc_sop", notes: "Incorporate Smith lab alignment angle.", createdAt: "2026-08-20" },
    { id: "task_email_chen", title: "Email Professor Chen", status: "Todo", priority: "Urgent", dueDate: T, applicationId: "app_princeton", professorId: "prof_chen", notes: "Follow up on Sep 1 outreach.", createdAt: "2026-09-01" },
    { id: "task_cmu_rec", title: "Request recommendation from Prof. Wang", status: "Todo", priority: "High", dueDate: d(3), applicationId: "app_cmu", createdAt: "2026-08-25" },
    { id: "task_mit_read", title: "Read Professor Park's latest paper", status: "Todo", priority: "High", dueDate: T, applicationId: "app_mit", professorId: "prof_park", createdAt: "2026-08-28" },
    { id: "task_uw_submit", title: "Submit UW application packet", status: "Todo", priority: "High", dueDate: d(5), applicationId: "app_uw", createdAt: "2026-09-01" },
    { id: "task_cv_rev", title: "Revise CV research section", status: "In Progress", priority: "Normal", dueDate: d(2), documentId: "doc_cv", createdAt: "2026-08-22" },
    { id: "task_cornell_fit", title: "Map Cornell faculty fit scores", status: "Todo", priority: "Normal", dueDate: d(7), applicationId: "app_cornell", createdAt: "2026-08-26" },
    { id: "task_nguyen_follow", title: "Follow up with Professor Nguyen", status: "Todo", priority: "Urgent", dueDate: d(-1), applicationId: "app_cmu", professorId: "prof_nguyen", createdAt: "2026-08-20" },
    { id: "task_toefl", title: "Confirm TOEFL score report sent", status: "Todo", priority: "Normal", dueDate: d(4), createdAt: "2026-08-30" },
    { id: "task_berkeley_scan", title: "Shortlist Berkeley EECS advisors", status: "Todo", priority: "Low", dueDate: d(10), applicationId: "app_berkeley", createdAt: "2026-08-18" },
    { id: "task_yale_prep", title: "Prepare Yale interview talking points", status: "In Progress", priority: "High", dueDate: d(2), applicationId: "app_yale", createdAt: "2026-09-02" },
    { id: "task_transcript", title: "Upload official transcript PDF", status: "Done", priority: "High", dueDate: d(-8), documentId: "doc_transcript", createdAt: "2026-08-10", completedAt: d(-7) },
    { id: "task_paper_notes", title: "Write notes on Chen 2025 NeurIPS paper", status: "Done", priority: "Normal", dueDate: d(-4), professorId: "prof_chen", createdAt: "2026-08-28", completedAt: d(-3) },
    { id: "task_columbia_done", title: "Finalize Columbia SOP version pin", status: "Done", priority: "Normal", dueDate: d(-6), applicationId: "app_columbia", createdAt: "2026-08-15", completedAt: d(-5) },
    { id: "task_uiuc_interest", title: "Decide whether to pursue UIUC seriously", status: "Todo", priority: "Low", dueDate: d(14), applicationId: "app_uiuc", createdAt: "2026-08-19" },
    { id: "task_rec_zhang", title: "Send materials to Prof. Zhang", status: "Todo", priority: "High", dueDate: d(6), applicationId: "app_stanford", createdAt: "2026-09-01" },
    { id: "task_calendar_block", title: "Block writing mornings for SOP", status: "Todo", priority: "Normal", dueDate: d(1), createdAt: "2026-09-03" },
    { id: "task_mit_draft", title: "Draft email to Professor Park", status: "In Progress", priority: "High", dueDate: d(1), applicationId: "app_mit", professorId: "prof_park", createdAt: "2026-09-02" },
    { id: "task_rec_li", title: "Confirm Prof. Li submission for Princeton", status: "Todo", priority: "Normal", dueDate: d(8), applicationId: "app_princeton", createdAt: "2026-08-29" },
    { id: "task_research_map", title: "Update research map for unlearning cluster", status: "Todo", priority: "Low", dueDate: d(12), createdAt: "2026-09-01" },
    { id: "task_funding_note", title: "Collect NSF GRFP / fellowship notes", status: "Todo", priority: "Normal", dueDate: d(9), createdAt: "2026-08-27" },
    { id: "task_smith_thanks", title: "Send thank-you note to Professor Smith", status: "Done", priority: "Normal", dueDate: d(-2), applicationId: "app_stanford", professorId: "prof_smith", createdAt: "2026-09-01", completedAt: d(-1) },
  ],

  documents: [
    {
      id: "doc_sop",
      title: "Statement of Purpose",
      category: "SOP",
      status: "Draft",
      applicationIds: ["app_stanford", "app_mit", "app_cmu", "app_princeton", "app_uw", "app_cornell"],
      versions: [
        { id: "sop_v1", version: 1, label: "v1", date: "2026-08-20", isCurrent: false, notes: "Outline" },
        { id: "sop_v2", version: 2, label: "v2", date: "2026-08-28", isCurrent: false },
        { id: "sop_v3", version: 3, label: "v3", date: "2026-09-02", isCurrent: false, notes: "Used for Columbia" },
        { id: "sop_v4", version: 4, label: "v4", date: "2026-09-06", isCurrent: true, notes: "Current working draft" },
      ],
      notes: "Stanford pins v4; MIT still on v3 framing.",
      createdAt: "2026-08-20",
      updatedAt: "2026-09-06",
    },
    {
      id: "doc_cv",
      title: "Curriculum Vitae",
      category: "CV",
      status: "Ready",
      applicationIds: ["app_stanford", "app_mit", "app_cmu", "app_princeton", "app_uw", "app_cornell", "app_columbia", "app_yale"],
      versions: [
        { id: "cv_v3", version: 3, label: "v3", date: "2026-08-15", isCurrent: false },
        { id: "cv_v4", version: 4, label: "v4", date: "2026-09-01", isCurrent: true },
      ],
      createdAt: "2026-07-01",
      updatedAt: "2026-09-01",
    },
    {
      id: "doc_transcript",
      title: "Official Transcript",
      category: "Transcript",
      status: "Ready",
      applicationIds: ["app_stanford", "app_mit", "app_cmu", "app_princeton", "app_uw", "app_columbia", "app_yale"],
      versions: [{ id: "tr_v1", version: 1, label: "v1", date: "2026-08-12", isCurrent: true, url: "#" }],
      createdAt: "2026-08-12",
      updatedAt: "2026-08-12",
    },
    {
      id: "doc_toefl",
      title: "TOEFL Score Report",
      category: "English Test",
      status: "Ready",
      applicationIds: ["app_stanford", "app_mit", "app_cmu", "app_princeton", "app_uw"],
      versions: [{ id: "toefl_v1", version: 1, label: "v1", date: "2026-06-10", isCurrent: true }],
      createdAt: "2026-06-10",
      updatedAt: "2026-06-10",
    },
    {
      id: "doc_writing",
      title: "Writing Sample — Unlearning Survey",
      category: "Other",
      status: "Draft",
      applicationIds: ["app_princeton", "app_cmu"],
      versions: [
        { id: "ws_v1", version: 1, label: "v1", date: "2026-08-25", isCurrent: true },
      ],
      createdAt: "2026-08-25",
      updatedAt: "2026-08-25",
    },
  ],

  recommendations: [
    { id: "rec_wang_stanford", recommenderName: "Prof. Wang", applicationId: "app_stanford", requestDate: "2026-08-20", deadline: "2026-11-20", status: "Submitted", notes: "Submitted via portal" },
    { id: "rec_li_stanford", recommenderName: "Prof. Li", applicationId: "app_stanford", requestDate: "2026-08-22", deadline: "2026-11-20", status: "Submitted" },
    { id: "rec_zhang_stanford", recommenderName: "Prof. Zhang", applicationId: "app_stanford", requestDate: "2026-09-01", deadline: "2026-11-20", status: "Requested" },
    { id: "rec_wang_princeton", recommenderName: "Prof. Wang", applicationId: "app_princeton", requestDate: "2026-08-20", deadline: "2026-12-01", status: "Submitted" },
    { id: "rec_li_princeton", recommenderName: "Prof. Li", applicationId: "app_princeton", requestDate: "2026-08-22", deadline: "2026-12-01", status: "Accepted" },
    { id: "rec_zhang_princeton", recommenderName: "Prof. Zhang", applicationId: "app_princeton", requestDate: undefined, deadline: "2026-12-01", status: "Not Requested" },
    { id: "rec_wang_cmu", recommenderName: "Prof. Wang", applicationId: "app_cmu", requestDate: "2026-08-25", deadline: "2026-12-01", status: "Accepted" },
    { id: "rec_li_cmu", recommenderName: "Prof. Li", applicationId: "app_cmu", requestDate: "2026-08-25", deadline: "2026-12-01", status: "Requested" },
    { id: "rec_zhang_cmu", recommenderName: "Prof. Zhang", applicationId: "app_cmu", requestDate: undefined, deadline: "2026-12-01", status: "Not Requested" },
    { id: "rec_wang_uw", recommenderName: "Prof. Wang", applicationId: "app_uw", requestDate: "2026-08-20", deadline: "2026-12-01", status: "Submitted" },
    { id: "rec_li_uw", recommenderName: "Prof. Li", applicationId: "app_uw", requestDate: "2026-08-22", deadline: "2026-12-01", status: "Submitted" },
    { id: "rec_zhang_uw", recommenderName: "Prof. Zhang", applicationId: "app_uw", requestDate: "2026-08-28", deadline: "2026-12-01", status: "Submitted" },
    { id: "rec_wang_yale", recommenderName: "Prof. Wang", applicationId: "app_yale", requestDate: "2026-07-20", deadline: "2026-11-15", status: "Submitted" },
    { id: "rec_li_yale", recommenderName: "Prof. Li", applicationId: "app_yale", requestDate: "2026-07-20", deadline: "2026-11-15", status: "Submitted" },
    { id: "rec_zhang_yale", recommenderName: "Prof. Zhang", applicationId: "app_yale", requestDate: "2026-07-22", deadline: "2026-11-15", status: "Submitted" },
  ],

  requirements: [
    { id: "req_st_cv", applicationId: "app_stanford", name: "CV", status: "Complete", required: true, linkedDocumentId: "doc_cv", category: "Document" },
    { id: "req_st_tr", applicationId: "app_stanford", name: "Transcript", status: "Complete", required: true, linkedDocumentId: "doc_transcript", category: "Document" },
    { id: "req_st_toefl", applicationId: "app_stanford", name: "TOEFL", status: "Complete", required: true, linkedDocumentId: "doc_toefl", category: "English" },
    { id: "req_st_sop", applicationId: "app_stanford", name: "SOP", status: "In Progress", required: true, linkedDocumentId: "doc_sop", category: "Document" },
    { id: "req_st_rec", applicationId: "app_stanford", name: "3 Recommendation Letters", status: "In Progress", required: true, category: "Recommendation" },
    { id: "req_pr_cv", applicationId: "app_princeton", name: "CV", status: "Complete", required: true, linkedDocumentId: "doc_cv", category: "Document" },
    { id: "req_pr_sop", applicationId: "app_princeton", name: "SOP", status: "In Progress", required: true, linkedDocumentId: "doc_sop", category: "Document" },
    { id: "req_pr_tr", applicationId: "app_princeton", name: "Transcript", status: "Complete", required: true, linkedDocumentId: "doc_transcript", category: "Document" },
    { id: "req_pr_toefl", applicationId: "app_princeton", name: "TOEFL", status: "Complete", required: true, linkedDocumentId: "doc_toefl", category: "English" },
    { id: "req_pr_rec", applicationId: "app_princeton", name: "3 Recommendation Letters", status: "In Progress", required: true, category: "Recommendation" },
    { id: "req_mit_sop", applicationId: "app_mit", name: "SOP", status: "Missing", required: true, linkedDocumentId: "doc_sop", category: "Document" },
    { id: "req_mit_cv", applicationId: "app_mit", name: "CV", status: "Complete", required: true, linkedDocumentId: "doc_cv", category: "Document" },
    { id: "req_mit_tr", applicationId: "app_mit", name: "Transcript", status: "Complete", required: true, linkedDocumentId: "doc_transcript", category: "Document" },
    { id: "req_cmu_sop", applicationId: "app_cmu", name: "SOP", status: "In Progress", required: true, linkedDocumentId: "doc_sop", category: "Document" },
    { id: "req_cmu_rec", applicationId: "app_cmu", name: "3 Recommendation Letters", status: "In Progress", required: true, category: "Recommendation" },
    { id: "req_uw_all", applicationId: "app_uw", name: "Application packet", status: "Complete", required: true, category: "Packet" },
    { id: "req_yale_interview", applicationId: "app_yale", name: "Interview preparation", status: "In Progress", required: true, category: "Interview" },
  ],

  englishTests: [
    { id: "eng_toefl", type: "TOEFL", score: 108, date: "2026-06-10", status: "Satisfied", notes: "Meets all tracked program minima." },
  ],

  programEnglishRequirements: [
    { id: "pe_stanford", programId: "prg_stanford_cs", type: "TOEFL", minimum: 100, required: true },
    { id: "pe_mit", programId: "prg_mit_eecs", type: "TOEFL", minimum: 100, required: true },
    { id: "pe_cmu", programId: "prg_cmu_cs", type: "TOEFL", minimum: 100, required: true },
    { id: "pe_princeton", programId: "prg_princeton_cs", type: "TOEFL", minimum: 100, required: true },
    { id: "pe_uw", programId: "prg_uw_cse", type: "TOEFL", minimum: 92, required: true },
  ],

  emails: [
    { id: "email_1", professorId: "prof_chen", applicationId: "app_princeton", date: "2026-08-28", subject: "Draft — interest in unlearning research", sender: "Alex Chen", recipient: "Prof. Wei Chen", content: "Drafted intro referencing Exact Machine Unlearning paper.", status: "Drafted", direction: "draft" },
    { id: "email_2", professorId: "prof_chen", applicationId: "app_princeton", date: "2026-09-01", subject: "Interest in joining your lab (PhD 2026–27)", sender: "Alex Chen", recipient: "Prof. Wei Chen", content: "Introduced background in machine unlearning and asked about openings.", status: "Contacted", direction: "outbound", followUpDate: d(2) },
    { id: "email_3", professorId: "prof_smith", applicationId: "app_stanford", date: "2026-08-25", subject: "Prospective PhD student — alignment research", sender: "Alex Chen", recipient: "Prof. Elena Smith", content: "Shared brief research summary and CV.", status: "Contacted", direction: "outbound" },
    { id: "email_4", professorId: "prof_smith", applicationId: "app_stanford", date: "2026-08-29", subject: "Re: Prospective PhD student — alignment research", sender: "Prof. Elena Smith", recipient: "Alex Chen", content: "Encouraged application; suggested reading recent preference optimization paper.", status: "Replied", direction: "inbound" },
    { id: "email_5", professorId: "prof_nguyen", applicationId: "app_cmu", date: "2026-08-18", subject: "Interest in AI agents research at CMU", sender: "Alex Chen", recipient: "Prof. Linh Nguyen", content: "Outreach email about hierarchical memory agents.", status: "Contacted", direction: "outbound", followUpDate: d(-1) },
    { id: "email_6", professorId: "prof_kim", applicationId: "app_uw", date: "2026-08-22", subject: "PhD inquiry — scalable unlearning", sender: "Alex Chen", recipient: "Prof. Soo-Jin Kim", content: "Asked about advising capacity.", status: "Contacted", direction: "outbound" },
    { id: "email_7", professorId: "prof_kim", applicationId: "app_uw", date: "2026-08-24", subject: "Re: PhD inquiry — scalable unlearning", sender: "Prof. Soo-Jin Kim", recipient: "Alex Chen", content: "Happy to review applications; taking 1–2 students.", status: "Replied", direction: "inbound" },
    { id: "email_8", professorId: "prof_berg", applicationId: "app_yale", date: "2026-08-10", subject: "Interview scheduling", sender: "Prof. Hannah Berg", recipient: "Alex Chen", content: "Proposed interview window for mid-September.", status: "Replied", direction: "inbound" },
  ],

  timelineEvents: [
    { id: "tl_1", type: "application_created", title: "Added Yale CS PhD", date: "2026-07-15", applicationId: "app_yale" },
    { id: "tl_2", type: "application_created", title: "Added Columbia CS PhD", date: "2026-07-20", applicationId: "app_columbia" },
    { id: "tl_3", type: "application_created", title: "Added Stanford CS PhD", date: "2026-08-01", applicationId: "app_stanford" },
    { id: "tl_4", type: "professor_added", title: "Added Professor Elena Smith", date: "2026-08-01", professorId: "prof_smith" },
    { id: "tl_5", type: "application_created", title: "Added Princeton CS PhD", date: "2026-08-05", applicationId: "app_princeton" },
    { id: "tl_6", type: "professor_added", title: "Added Professor Wei Chen", date: "2026-08-05", professorId: "prof_chen" },
    { id: "tl_7", type: "paper_added", title: "Added Chen et al. NeurIPS 2025 paper", date: "2026-08-06", paperId: "paper_1", professorId: "prof_chen" },
    { id: "tl_8", type: "email_recorded", title: "Contacted Professor Nguyen", date: "2026-08-18", professorId: "prof_nguyen", applicationId: "app_cmu" },
    { id: "tl_9", type: "document_uploaded", title: "Uploaded official transcript", date: "2026-08-12", documentId: "doc_transcript" },
    { id: "tl_10", type: "email_recorded", title: "Contacted Professor Chen", date: "2026-09-01", professorId: "prof_chen", applicationId: "app_princeton" },
    { id: "tl_11", type: "email_recorded", title: "Professor Smith replied", date: "2026-08-29", professorId: "prof_smith", applicationId: "app_stanford" },
    { id: "tl_12", type: "document_version", title: "Stanford SOP v3 completed", date: "2026-09-02", documentId: "doc_sop", applicationId: "app_stanford" },
    { id: "tl_13", type: "task_completed", title: "Wrote notes on Chen 2025 paper", date: d(-3), taskId: "task_paper_notes", professorId: "prof_chen" },
    { id: "tl_14", type: "application_status_changed", title: "Columbia marked Submitted", date: d(-5), applicationId: "app_columbia", meta: { status: "Submitted" } },
    { id: "tl_15", type: "application_status_changed", title: "Yale moved to Interview", date: d(-2), applicationId: "app_yale", meta: { status: "Interview" } },
    { id: "tl_16", type: "document_version", title: "SOP advanced to v4", date: "2026-09-06", documentId: "doc_sop" },
    { id: "tl_17", type: "task_completed", title: "Sent thank-you note to Professor Smith", date: d(-1), taskId: "task_smith_thanks", professorId: "prof_smith" },
    { id: "tl_18", type: "professor_linked", title: "Linked Professor Chen to Stanford", date: "2026-08-21", professorId: "prof_chen", applicationId: "app_stanford" },
  ],
};
